'\" t
.\" Copyright (c) 1998, 2002, 2005 P. N. Hilfinger
.\" All Rights Reserved
.TH GET-SUBM 1 "22 Dec 2005"
.SH NAME
get-subm \- Unpack submission from submit for inspection
.SH SYNOPSIS
.B get-subm
.I assignment
.IR login [. timestamp ]

.SH DESCRIPTION
.LP
The
.B get-subm
command unpacks a set of files that a student has submitted using
.BR submit (1)
into the current directory.  The operands are the assignment name, the login
of the student, and (optionally) a timestamp in the form 
.IR yyyymmddhhmm ,
as produced by 
.BR file-submissions (1).
In the absence of a timestamp, this unpacks the latest submission.
For
assignments with partnerships, the resulting files will include 
MY.PARTNERS, created by 
.BR submit ,
containing a list of all students'
logins in the partnership.

.SH "EXIT STATUS"
.LP
Returns an exit code of 0 on normal completion, and non-zero in case of error.

.SH "SEE ALSO"
.BR submit (1),
.BR file-submissions (1),
.BR get-bug (1)

.SH IDENTIFICATION
Author: Paul N. Hilfinger.  
Copyright \(co 1998, 2002, 2005

