'\" t
.\" Copyright (c) 2005 P. N. Hilfinger
.\" All Rights Reserved
.TH GRADE-ENTRIES 1 "23 May 2005"
.SH NAME
grade-entries \- List grades for a given assignment
.SH SYNOPSIS
.B grade-entries
.I assignment-name
.br
.SH DESCRIPTION
.LP
The
.B grade-entries
program
produces a grade-entry file (in the format acceptable to 
.BR enter-grades (1))
for a given assignment.   This file will contain only the latest 
entries for each distinct login.

.SH "EXIT STATUS"
.LP
This command returns 0 in the absence of anomalies, 1 if there are problems.

.SH "SEE ALSO"
.BR make-grade-file (1).

.SH IDENTIFICATION
Author: Paul N. Hilfinger.  
Copyright \(co 2001, 2005
