'\" t
.\" Copyright (c) 2002, 2005, 2008 P. N. Hilfinger
.\" All Rights Reserved
.TH LIST-PARTNERS 1 "6 Jan 2008"
.SH NAME
list-partners \- Find partnerships in a set of submissions
.SH SYNOPSIS
.B list-partners
[
.B \-h
] 
.I assign 
[
.I login
]
.SH DESCRIPTION
.LP
List partnership information for \fIlogin\fP on assignment \fIassign\fP, or for
all logins in \fIlogin\fP is defaulted.  The program will warn of
anomalies, such as partnerships for the same student that conflict.

.SH "SEE ALSO"
.BR submit (1)

.SH IDENTIFICATION
Author: Paul N. Hilfinger.  
Copyright \(co 2002, 2005, 2008

