'\" t
.\" Copyright (c) 1998, 2002 P. N. Hilfinger
.\" All Rights Reserved
.TH ?? 1 "11 Mar 2002"
.SH NAME
lookat \- Unpack a submission
.SH SYNOPSIS
.B lookat
[
.B \-d
.I dir
]
.IR login [. timestamp ]

.SH DESCRIPTION
.LP
The
.B lookat
command unpacks a submission previously obtained by 
.BR get-submissions (1)
into a directory for examination.  One may specify either a 
.IR login ,
which unpacks the latest submission in the current directory for that login, 
or 
.IR login.timestamp ,
which picks a specific submission.  
.PP 
.B lookat
unpacks the indicated set of submitted files into a directory
.IR dir ,
or by default, into directory
.BR LOOK ,
clearing any previous contents of that directory.

.SH OPTIONS
.TP 12
.BI \-d dir
Directory into which to unpack submission

.SH "SEE ALSO"
.BR get-submissions (1)

.SH IDENTIFICATION
Author: Paul N. Hilfinger.  
Copyright \(co 1998, 2002
