'\" t
.\" Copyright (c) 1998, 2002, 2005 P. N. Hilfinger
.\" All Rights Reserved
.TH MAKE-GRADE-BOOK 1 "23 May 2005"
.SH NAME
make-grade-book \- Create a grade book database file out of collected rosters
.SH SYNOPSIS
.B make-grade-book

.SH DESCRIPTION
.LP
The
.B make-grade-book
command takes the rosters entered by 
.B enter-grades
and creates grade book files usable by 
.B glookup
and
.BR assign-letter-grades .

.LP
In general, it should not be necessary to use this program directly, since
.B enter-grades 
calls it automatically.  It is sometimes useful, however, if files get out 
of sync for some reason (such as when all grades have been entered before 
the deadline indicated in the params file).

.SH "EXIT STATUS"
.LP
Returns an exit code of 0 on normal completion, 
and non-zero in case of error.

.SH "SEE ALSO"
.BR assign-letter-grades (1),
.BR glookup (1),

.SH IDENTIFICATION
Author: Paul N. Hilfinger.  
Copyright \(co 1998, 2002, 2005
