'\" t
.\" Copyright (c) 1998, 2002 P. N. Hilfinger
.\" All Rights Reserved
.TH registration 1 "11 Mar 2002"
.SH NAME
register, re-register, check-register \- Create or check an entry in the class registration database
.SH SYNOPSIS
.B register
.br
.B re-register
.br
.B check-register

.SH DESCRIPTION
.LP
The 
.B register
command should typically be included in students'
.B .login
files.  It asks for students names and SIDs, and records these in a central 
directory, protected so that only the students and designated staff may read
them.
.LP
If there is already a registration entry for the current login, 
.B register
will do nothing.  The 
.B re-register 
program has the same behavior as 
.BR register ,
but it will override an existing entry.
.LP
The 
.B check-register
command will print any registration information recorded for the current 
login.

.SH IDENTIFICATION
Author: Paul N. Hilfinger.  
Copyright \(co 1998, 2002
