'\" t
.\" Copyright (c) 1998, 2002 P. N. Hilfinger
.\" All Rights Reserved
.TH RUN-TESTS 1 "11 Mar 2002"
.SH NAME
run-tests \- Run test scripts on submissions to automated grader
.SH SYNOPSIS
.B run-tests
[
.B \-h 
] [
.B \-a
]
.I assignment
[
.I login[.timestamp] ... 
]

.SH DESCRIPTION
.LP
The
.B run-tests
command runs the tests prescribed for 
.I assignment
on all submissions by 
the 
.BR submit (1)
program for which they have not yet been run.  Logs of these runs
go into the appropriate directories
.BI .../logs/ok/ assignment
and 
.BI .../logs/fail/ assignment.
in the master grading directory.
The tests run on submissions from each \fIlogin\fR specified (by default,
all submissions).  If a specific timestamp is provided, only that submission
is tested.  Otherwise, only the latest submissions for all logins are tested,
except with the  
.B \-a
switch, with indicates that all submissions for 
logins without specific timestamps are to be tested.
.LP
This command does not mail out results.  See
.BR mail-results (1).

.SH OPTIONS
.TP 12
.B \-a
Run tests on all submissions for each login, if no timestamp is provided.

.SH "EXIT STATUS"
.LP
Returns an exit code of 0 on normal completion, and non-zero in case of error.

.SH "SEE ALSO"
.BR submit (1),
.BR test-subm (1),
.BR mail-results (1)

.SH IDENTIFICATION
Author: Paul N. Hilfinger.  
