'\" t
.\" Copyright (c) 1998, 2002, 2004, 2005 P. N. Hilfinger
.\" All Rights Reserved
.TH CHECK-READER-GRADES 1 "23 May 2005"
.SH NAME
check-reader-grades \- Fetch and archive grading rosters
.SH SYNOPSIS
.B check-reader-grades
[
.B \-hn
] [
.IR reader-login \|.\|.\|.
]

.SH DESCRIPTION
.LP
The
.B check-reader-grades
command 
checks for overdue grade reports from
the listed readers (by default, all readers).
With \fB-n\fP,  also mails reminders to the readers.

.SH OPTIONS
.TP 12
.B \-n
Do not mail reminders to the readers.

.SH "EXIT STATUS"
.LP
Returns an exit code of 0 on normal completion, and non-zero in case of error.

.SH "SEE ALSO"
.BR make-grade-book (1),
.BR enter-grades (1),

.SH IDENTIFICATION
Author: Paul N. Hilfinger.  
Copyright \(co 1998, 2002, 2004, 2005
