'\" t
.\" Copyright (c) 2002, 2003, 2004 P. N. Hilfinger
.\" All Rights Reserved
.TH INIT-GRADING 1 "18 Mar 2004"
.SH NAME
init-grading \- Miscellaneous functions on the grading database
.SH SYNOPSIS
.B init-grading
.B \-p
[
.B \-o
.I parameter-file
]
.br
.B init-grading
.B \-i
[
.B \-f
.I parameter-file
]

.SH DESCRIPTION
.LP
The
.B init-grading
command performs (re)initialization functions on the grading system.  
With 
.BR \-p ,
it creates a blank parameter file in 
.I parameter-file,
which defaults to `params'.  After you edit this file, you may initialize
the grading system with the 
.B \-i
form of the command, which creates the necessary directories (if needed) and
installs
.I parameter-file
in them.

.SH OPTIONS
.TP 12
.BI \-f " parameter-file"
Name of file used with \fB\-i\fP to supply grading software's parameters.
.TP
.B \-i
Initialize grading files.
.TP
.BI \-o " file" 
File in which to put output for \fB-p\P option.
.TP
.B \-p
Create blank parameter file for editing.

.SH "EXIT STATUS"
.LP
Returns an exit code of 0 on normal completion, and non-zero in case of error.

.SH IDENTIFICATION
Author: Paul N. Hilfinger.  
Copyright \(co 2002, 2003, 2004
