.ds p \&\s-1SUBMIT\s0
.if n .ds - \%--
.if t .ds - \(em
.if !\n(.g \{\
.	if !\w|\*(lq| \{\
.		ds lq ``
.		if \w'\(lq' .ds lq "\(lq
.	\}
.	if !\w|\*(rq| \{\
.		ds rq ''
.		if \w'\(rq' .ds rq "\(rq
.	\}
.\}
.de PE
.sp \\n()Pu
.ne 2
.nf
.IP
..
.de EP
.fi
.PP
.sp \\n()Pu
..
.TH BUG-SUBMIT 1
.SH NAME
bug-submit \- Submit a request for assistance on an assignment
.SH SYNOPSIS
.B bug-submit
.I assignment-name
.SH DESCRIPTION (FOR USERS)
The 
.B bug-submit
command packages a set of files in the current directory and sends
them to an appropriate account with a request for assistance.  It is 
intended to be used to submit a ``bug report'' about one's own program to
a TA or instructor.  
The
.I assignment-name
operand must be one of a set of recognized assignment names.  
The command will prompt the user about each of the 
files in (or under) the current directory, and will include any the user
indicates in the submission. One of the files must be named 
.B ERROR 
and should contain a brief description of your problem or question.  

.SH "SEE ALSO"
.BR submit (1)

.SH IDENTIFICATION
Author: Paul N. Hilfinger. Copyright \(co 1998, 2002
