'\" t
.\" Copyright (c) 1998, 2002 P. N. Hilfinger
.\" All Rights Reserved
.TH MAKE-MAIN-ROSTER 1 "11 Mar 2002"
.SH NAME
make-main-roster \- Create class roster from registration data
.SH SYNOPSIS
.B make-main-roster

.SH DESCRIPTION
.LP
The
.B make-main-roster
command creates a central roster of all students.
This roster is used by
.BR make-roster
and
.BR make-grade-book .
Normally, 
.B make-main-roster
is called as needed by the commands that need it.

.SH "EXIT STATUS"
.LP
Returns an exit code of 0 on normal completion, and non-zero in case of error.

.SH "SEE ALSO"
.BR grade (1),
.BR make-grade-book (1),
.BR make-roster (1)

.SH IDENTIFICATION
Author: Paul N. Hilfinger.  
Copyright \(co 1998, 2002
