'\" t
.\" Copyright (c) 2002 P. N. Hilfinger
.\" All Rights Reserved
.TH TEST-SUBM 1 "03 Sep 2003"
.SH NAME
test-subm \- Run tests on submission in current directory
.SH SYNOPSIS
.B test-subm
[
.B \-h
] 
.I assignment
[
.I log-file
]

.SH DESCRIPTION
.LP
The
.B test-subm
command runs the prescribed tests (as per
.BR run-tests (1))
on the submission that has been unpacked (by 
.BR get-subm (1))
into the current directory.
The submission log normally produced by
.BR run-tests
is written to the file \fIlog-file\fP, or by default to the standard output.

.SH "WARNING"
.LP
Whenever you run students' programs, there is always the possibility of
mischief.  You might consider running this program only in an account
different from the class master, such as the automated-grading account.

.SH "EXIT STATUS"
.LP
Returns an exit code of 0 on successful completion of all tests,
1 if the tests run but are not passed, and 2 if the tests cannot be run.

.SH "SEE ALSO"
.BR run-tests (1)
.BR get-subm (1)

.SH IDENTIFICATION
Author: Paul N. Hilfinger.  
